input_folder: ~/Dropbox/Chris Share/Bob is Doomed/PSDs
output_folder: ./bidTestOutput
start_date: 2012-12-26
strip_filename_pattern: !ruby/regexp /bid_([0-9]{2})_([0-9]{3}).psd/
page_template: bidTemplate.haml
blacklist: [01-011,01-014]
# post_weekdays contains a list of days of the week on which strips will be posted; (0 = Sunday, 1 = Monday, ... , 6 = Saturday)
post_weekdays: [1,3,5]